### ISSUE TITLE
storm events chart axis minimum

### ISSUE THREAD

**Issue by ljpaul** [soichih/apred#10]
Set axis of storm events graph to have minimum of zero. When there are no storm events (e.g. FIPS 02105) it displays as -1,-1 for the minimum for the chart.

**Comment by soichih** [comment]
I am going to just show that the there is no storm data if there is no storm data

![image](https://user-images.githubusercontent.com/923896/93896760-513b1100-fcbf-11ea-835b-22df4fd7180e.png)
