### ISSUE TITLE
Population Source

### ISSUE THREAD

**Issue by blj4** [soichih/apred#100]
On the County Detail tab, the Population number is not from the ACS. See below.

![image](https://user-images.githubusercontent.com/73551173/109995412-422fa480-7cdc-11eb-87fb-15bbc854b3f8.png)

That is the Census Bureau's population estimate. There are also 2019 estimates available now, so that can be updated to the latest year.

HOWEVER, the Population Density data is ACS 5-year estimate data. You might want to switch to all ACS for this, so you aren't comparing two different population numbers.

**Comment by soichih** [comment]
Updated to use 2019 dataset.

**Comment by blj4** [comment]
Hey, Soichi. I just checked again and I'm still seeing the same population number as before. Is this a caching issue? The number should be 964,582 for Marion County, Indiana.

![image](https://user-images.githubusercontent.com/73551173/110009703-5f1fa400-7ceb-11eb-83f5-ed9b1b945a3e.png)

**Comment by soichih** [comment]
Sorry I haven't released the update to the production instance. Here is the number from my dev instance.

![image](https://user-images.githubusercontent.com/923896/110018732-9d21c580-7cf5-11eb-8b79-3d5d6b8fdb15.png)

**Comment by soichih** [comment]
I just saw this comment

> HOWEVER, the Population Density data is ACS 5-year estimate data. You might want to switch to all ACS for this, so you aren't comparing two different population numbers.

Here is the query I am using to pull these records
> https://github.com/soichih/apred/blob/master/backend/bin/extract/statsamerica_acs.js#L72
Could you send me the correct query that I should be using?

**Comment by blj4** [comment]
I actually think this is fine as it is, as long as you change the source for the Population to Census Bureau (instead of ACS). The age and race data comes from the Census Bureau, so it’s probably better to leave the total population from the Census Bureau, as well. The population density is being pulled from ACS because that’s the only way we currently have it stored in the database.

I’ll ask Carol if this is okay or if we should create a new table with population density calculated from the Census Bureau’s population estimates, rather than ACS.

**Comment by blj4** [comment]
One more thing -

As it currently is shown on the tool, it should be Census Bureau 2019 for the Population source. But it should be ACS as the Population Density source. That can be updated to 2019 data, as well.

The Population History and Racial Makeup History are also Census Bureau population estimates.
