### ISSUE TITLE
Population Graphs

### ISSUE THREAD

**Issue by blj4** [soichih/apred#101]
I find these graphs under the population items pretty confusing. I expected to see Marion County's population over time and it took me a minute to understand that this was the number of counties in Indiana and the U.S. that have different population numbers. Perhaps this should be labeled more clearly.

I would also add commas in the numbers in the thousands as highlighted below.

![image](https://user-images.githubusercontent.com/73551173/109996079-e1549c00-7cdc-11eb-836a-f63abf9ff0fc.png)

Also, this isn't people per square mile. This is total population. So, it should say 50,000 people for each bar.

**Comment by soichih** [comment]
I've fixed the xaxis legend issue, and renamed the renamed the Y axis legend names.

![image](https://user-images.githubusercontent.com/923896/110018283-24226e00-7cf5-11eb-9e3f-9fa984517128.png)
