### ISSUE TITLE
Racial Makeup Legend

### ISSUE THREAD

**Issue by blj4** [soichih/apred#104]
I would consider explaining what AIAN is - American Indian or Alaskan Native.

![image](https://user-images.githubusercontent.com/73551173/109998268-0f3ae000-7cdf-11eb-9958-fd438e677812.png)

**Comment by soichih** [comment]
Updated
![image](https://user-images.githubusercontent.com/923896/110016202-c42ac800-7cf2-11eb-8e56-d0ae8ada4399.png)
