### ISSUE TITLE
Add Percentages to Racial Makeup?

### ISSUE THREAD

**Issue by blj4** [soichih/apred#105]
Might it be helpful to add percentages of the total for the racial makeup graph? They are available in the Population History graph.

![image](https://user-images.githubusercontent.com/73551173/109998656-748ed100-7cdf-11eb-8cc1-15ff97977632.png)

**Comment by soichih** [comment]
We currently don't show percentages on either population graph, but we could compute it and display it. Anyone else think we should implement this?

**Comment by iobik** [comment]
@soichih @ljpaul Are there concerns you would like to share about showing the percentages?

**Comment by iobik** [comment]
@soichih @ljpaul What is the status of this issue?

**Comment by soichih** [comment]
Added percentages

![image](https://user-images.githubusercontent.com/923896/113590003-1582eb80-9600-11eb-89ce-0c940cb58eb8.png)

**Comment by iobik** [comment]
This update looks really good and provides more context than. Thank you again @soichih, I appreciate you fixing these issues.
