### ISSUE TITLE
BEA Data

### ISSUE THREAD

**Issue by blj4** [soichih/apred#106]
Where is the GDP number coming from?

![image](https://user-images.githubusercontent.com/73551173/110000096-ed425d00-7ce0-11eb-86ba-0f150d273935.png)

I can't find a match in our database. Also, I would suggest listing the year of the data that is shown.

**Comment by soichih** [comment]
I am currently using the following query

```
SELECT gcp_c FROM bea_gdp_uscnty WHERE linecd = 0001 AND YEAR = 2018
```

to pull this number. So it's hardcoded to 2018. Should I update it?

**Comment by soichih** [comment]
I just re-run statsamerica_bea_gdp script. I am now seeing the same number!

"gdp": 93236369,

I am not running statsamerica_bea_gdp via cron. I had an impression that
this data won't change once I cache it on my end. Should I be
re-downloading this periodically?

**Comment by blj4** [comment]
BEA releases this data on an annual basis, but when a new year is released, they also revise previous years of data. So, this should be re-downloaded on an annual basis to capture the new year and the revised old data. This year, BEA released the new year and revised years on December 9, 2020.

From: Soichi Hayashi ***@***.***>
Sent: Tuesday, March 23, 2021 3:27 PM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Author ***@***.***>
Subject: [External] Re: [soichih/apred] BEA Data (#106)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.

I just re-run statsamerica_bea_gdp script. I am now seeing the same number!

"gdp": 93236369,

I am not running statsamerica_bea_gdp via cron. I had an impression that
this data won't change once I cache it on my end. Should I be
re-downloading this periodically?

**Comment by iobik** [comment]
@soichih @blj4 Where are we on this issue?

**Comment by blj4** [comment]
As long as Soichi has set this to re-download on an annual basis, it is done.

From: iobik ***@***.***>
Sent: Monday, March 29, 2021 10:29 PM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [soichih/apred] BEA Data (#106)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


@soichih<https://github.com/soichih> @blj4<https://github.com/blj4> Where are we on this issue?

**Comment by iobik** [comment]
@soichih Please, can you confirm that you have "set this to re-download on an annual basis?"

**Comment by soichih** [comment]
I've moved `./extract/statsamerica_bea_gdp.js` to monthly cron job

**Comment by iobik** [comment]
Great job! Thank you @soichih
