### ISSUE TITLE
Per Capita Income Source

### ISSUE THREAD

**Issue by blj4** [soichih/apred#107]
The Per Capita Income data is not ACS data. It is coming from the Bureau of Economic Analysis. I would also put the year for this data, which is 2019.

![image](https://user-images.githubusercontent.com/73551173/110000681-925d3580-7ce1-11eb-8957-fb20b535f472.png)

**Comment by iobik** [comment]
@soichih What do you have to say about this issue?

**Comment by soichih** [comment]
I am pulling data from `stats4.dbo.pcpi_uscnty` table. Is this BEA data?

**Comment by iobik** [comment]
@blj4  Are we pulling this data from the right source?

**Comment by blj4** [comment]
Yes, the data that is coming from pcpi_uscnty is BEA data, not ACS data. So basically the source just needs to change.

From: iobik ***@***.***>
Sent: Sunday, March 28, 2021 7:50 PM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [soichih/apred] Per Capita Income Source (#107)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


@blj4<https://github.com/blj4> Are we pulling this data from the right source?

**Comment by soichih** [comment]
I've updated the label. Do I need to change other income related sections to BEA also?

**Comment by blj4** [comment]
No.

Median Household Income and Per Capita Money Income are coming from ACS. GDP, Per Capita Income, and Per Capita Personal Income are coming from BEA.

I did notice, however, that Median Household Income is still showing the 2018 data (even though the label says 2019). That needs to be updated to the latest.

From: Soichi Hayashi ***@***.***>
Sent: Monday, March 29, 2021 3:35 PM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [soichih/apred] Per Capita Income Source (#107)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


I've updated the label. Do I need to change other income related sections to BEA also?

**Comment by soichih** [comment]
> I did notice, however, that Median Household Income is still showing the 2018 data 
Looks like I forgot to cache it on production instance. I just did that now. You should be seeing the 2019 data.

**Comment by blj4** [comment]
Looks great now!

From: Soichi Hayashi ***@***.***>
Sent: Monday, March 29, 2021 4:15 PM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [soichih/apred] Per Capita Income Source (#107)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


I did notice, however, that Median Household Income is still showing the 2018 data

Looks like I forgot to cache it on production instance. I just did that now. You should be seeing the 2019 data.

**Comment by iobik** [comment]
Awesome! Looks good now. Thank you all
