### ISSUE TITLE
Per Capita Income and Median Household Income Labels

### ISSUE THREAD

**Issue by blj4** [soichih/apred#108]
I am confused by the 2 and 5 in the Per Capita Income and Median Household Income graphs. See below.

![image](https://user-images.githubusercontent.com/73551173/110000899-cd5f6900-7ce1-11eb-8321-6f5915cfe93b.png)

Should that be 20 and 50? And then 200 and 500?

**Comment by iobik** [comment]
@ljpaul @soichih What is the update on this issue?

**Comment by soichih** [comment]
I've removed those subticks.

**Comment by iobik** [comment]
Excellent! Thank you for making the changes.
