### ISSUE TITLE
Graph Labeling on X-Axis

### ISSUE THREAD

**Issue by blj4** [soichih/apred#109]
There are multiple issues with the labels under the graphs. For example, for GDP, this isn't population. That should probably say GDP ($5 million for each bar). For Per Capita Income, it should say Per Capita Income ($5,000 for each bar). For Median Household Income, it should say Median Household Income ($5,000 for each bar).

![image](https://user-images.githubusercontent.com/73551173/110001620-89209880-7ce2-11eb-9bf5-38af932375c8.png)

**Comment by soichih** [comment]
The bucket size comes from the ETL script and it's dynamic. "$5m" is concise and probably better, but for now I've just added number formatting. 

![image](https://user-images.githubusercontent.com/923896/112056135-0d21af80-8b2e-11eb-9f93-b1674c43c604.png)

I am currently using vue-formatter (https://github.com/kevinongko/vue-numeric) and it doesn't seem to provide the formatting option to turn a number (like 5000000) to human friendly strings "$5m", unfortunately.

**Comment by iobik** [comment]
@blj4 @soichih Are we good on this issue?

**Comment by blj4** [comment]
I think so, yes. Soichi changed the labels under the graphs.

From: iobik ***@***.***>
Sent: Monday, April 5, 2021 9:13 AM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [soichih/apred] Graph Labeling on X-Axis (#109)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


@blj4<https://github.com/blj4> @soichih<https://github.com/soichih> Are we good on this issue?

**Comment by iobik** [comment]
Perfect! Thank you for the response.
