### ISSUE TITLE
Median Household Income

### ISSUE THREAD

**Issue by blj4** [soichih/apred#110]
The Median Household Income data can be updated to 2019 ACS 5-year estimates.

![image](https://user-images.githubusercontent.com/73551173/110002292-3a273300-7ce3-11eb-83a5-cea5a62c2d91.png)

**Comment by soichih** [comment]
updated to pull 2019 data.

**Comment by iobik** [comment]
I believe this issue has been resolved. Let me know if you think otherwise. Thanks
