### ISSUE TITLE
Per Capita Money Income Graph

### ISSUE THREAD

**Issue by blj4** [soichih/apred#111]
I don't think it's necessary to show the margin of error on the data for Per Capita Money Income.

![image](https://user-images.githubusercontent.com/73551173/110002702-b1f55d80-7ce3-11eb-976e-88194f4cd824.png)

Also, I think it would be more easily understandable if it was written as $27,251 instead of 27.251k$. The labels on the y-axis could be changed $24,000, as well. The same is true for the Per Capita Personal Income graph below.

**Comment by iobik** [comment]
Resolved. Thank you!
