### ISSUE TITLE
Top Industries Percentages

### ISSUE THREAD

**Issue by blj4** [soichih/apred#114]
How are the percentages being calculated for the Top Industries? I just took the industry employment divided by the total employment for that county and it's not matching.

Also, the numbers could be formatted more clearly when you hover. For example, this could say 47,677 instead of 47.67716k.

![image](https://user-images.githubusercontent.com/73551173/110005647-ba02cc80-7ce6-11eb-9409-71337827bf1d.png)

**Comment by soichih** [comment]
Updated

**Comment by iobik** [comment]
Thank you! Looks good now.
