### ISSUE TITLE
Unemployment Rate Report Date

### ISSUE THREAD

**Issue by blj4** [soichih/apred#115]
It looks like the report date listed for the Unemployment Rate data isn't refreshing. It still says 11/30/2020, but this is December 2020 data pulling through.

![image](https://user-images.githubusercontent.com/73551173/110006219-62189580-7ce7-11eb-8410-5b107f6fde6f.png)

**Comment by soichih** [comment]
The data is for "2020/12", but it is stored as UTC, so when it's displayed on the browser it is converted to the local timestamp. For EST timezone (UTC-5), it would shows up as 11/30 (7PM). I will update so that it will show in UTC.
