### ISSUE TITLE
Employment History Explanation

### ISSUE THREAD

**Issue by blj4** [soichih/apred#116]
I would add a note somewhere for the Employment History that this is also the 24-month sum of employed and unemployed people for that geography. Otherwise, people will think that's insanely too high.

![image](https://user-images.githubusercontent.com/73551173/110006591-d6ebcf80-7ce7-11eb-825e-59f42b9f4eb5.png)

I would also format the numbers so they're easily read when you hover.

**Comment by soichih** [comment]
I believe we decided that we will divide these numbers by 24 on the DB end? Or should I do that at the UI end?

**Comment by blj4** [comment]
Those numbers are being stored in the database as 24-month sums so that the calculation for the 24-month unemployment rate can easily be done. It might be easier for you to do it on the UI end.

**Comment by soichih** [comment]
Updated to show values /24.

**Comment by iobik** [comment]
@soichih @blj4 Are we good on this issue?

**Comment by blj4** [comment]
Yes, this is now pulling the correct numbers. Can you format it without the decimal and k to make it more readable?

From: iobik ***@***.***>
Sent: Monday, March 29, 2021 10:34 PM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [soichih/apred] Employment History Explanation (#116)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


@soichih<https://github.com/soichih> @blj4<https://github.com/blj4> Are we good on this issue?

**Comment by iobik** [comment]
@soichih Please can you take care of the above comment by Brittany? Thank you

**Comment by soichih** [comment]
Updated 

![image](https://user-images.githubusercontent.com/923896/113588273-ee2b1f00-95fd-11eb-9c62-c8932ec82888.png)

**Comment by iobik** [comment]
Awesome! Thank you for updating the visualization.
