### ISSUE TITLE
Data Sources

### ISSUE THREAD

**Issue by blj4** [soichih/apred#117]
The Data Sources notes at the bottom of the page need to be revised. See below.

![image](https://user-images.githubusercontent.com/73551173/110007034-48c41900-7ce8-11eb-9010-a5800b4cef44.png)

The population estimate, racial makeup, and population history data are coming from the Census Bureau's Population Estimates by Age, Sex, Race, and Hispanic Origin.

The Population Density, Median Household Income, and Per Capita Money Income are coming from the Census Bureau's American Community Survey, 5-year estimates.

The GDP, Per Capita Income, and Per Capita Personal Income (which is the same as the Per Capita Income data that is currently being displayed) are from the Bureau of Economic Analysis.

The Top Industries data is from the Census of Employment and Wages data from the Bureau of Labor Statistics and the Unemployment Rate data is LAUS from BLS.

**Comment by soichih** [comment]
Updated

**Comment by iobik** [comment]
@soichih I don't see the industry source listed on the update.

**Comment by iobik** [comment]
I can now see the update. Thank you
