### ISSUE TITLE
Formatting Business Vulnerability Numbers on Graphs

### ISSUE THREAD

**Issue by blj4** [soichih/apred#120]
This isn't necessary, but I think it'd be easier to understand if you formatted the numbers in the thousands to just the real number when you hover. For example:

![image](https://user-images.githubusercontent.com/73551173/110157468-344e5200-7db6-11eb-841b-ffc521ba40f2.png)

Make this say 12,215 instead of 12.215k.

**Comment by soichih** [comment]
I will update to this

![image](https://user-images.githubusercontent.com/923896/112046606-a34fd880-8b22-11eb-9cdb-db18c6a9cb46.png)

**Comment by iobik** [comment]
This looks good. Thanks
