### ISSUE TITLE
Business Vulnerability Source Data

### ISSUE THREAD

**Issue by blj4** [soichih/apred#121]
I would add somewhere on the Business Vulnerability tab what the source of the data is. The Census Bureau's County Business Patterns.

**Comment by soichih** [comment]
How about ...

![image](https://user-images.githubusercontent.com/923896/112044550-52d77b80-8b20-11eb-830b-1cd4a9dd4c7f.png)

**Comment by iobik** [comment]
I think that looks good to me. Thanks
