### ISSUE TITLE
Make it more obvious that a county potentially qualifies for EDA disaster supplemental funding.

### ISSUE THREAD

**Issue by iobik** [soichih/apred#13]
Rearrange the order of these details to place the disaster events and the eligibility information on the same line. This will help to draw attention to the information we want the users to act on 

a) 'This incident may be eligible for 2019 Disaster Supplemental funding'  move to the top right. 
b) 'Hazard Mitigation, Individuals and Households etc.'  move down to the left.

![image](https://user-images.githubusercontent.com/71714873/93899164-08d12280-fcc2-11ea-8b61-4cea55bb2f16.png)

**Comment by soichih** [comment]
Like this? 
![image](https://user-images.githubusercontent.com/923896/93904071-6c118380-fcc7-11ea-9f15-dc443da1689a.png)

**Comment by iobik** [comment]
> Like this?
> ![image](https://user-images.githubusercontent.com/923896/93904071-6c118380-fcc7-11ea-9f15-dc443da1689a.png)

Yes. Looks good.
