### ISSUE TITLE
On hover, remove K at the end of the population data in the dashboard section

### ISSUE THREAD

**Issue by iobik** [soichih/apred#16]
The numbers are already written in full. There is no need to have k at the end. E.g. 14,171 instead of 14.171k. Population data >> dashboard section

![image](https://user-images.githubusercontent.com/71714873/93902163-408d9980-fcc5-11ea-90a5-acdcfe316a7e.png)

**Comment by soichih** [comment]
This is similar to #19, but K is actually needed as 14.171 means "14 and 171/1000th" in this case. It's different from "14,171" which *is* the full amount.
