### ISSUE TITLE
Disaster Info missing for Polk County, Florida

### ISSUE THREAD

**Issue by iobik** [soichih/apred#18]
"I’m specifically looking at Polk County, Florida and trying to compare the disasters to what I’m seeing in stats4.dbo.fema_disasters. Why isn’t Hurricane Dorian and Hurricane Matthew showing? Is there some kind of filter that I’m missing?"

**Comment by soichih** [comment]
FYI. Here is the SQL query I am executing to query for "recent" FEMA diasters 
> `SELECT * from FEMA_disasters WHERE declarationType = 'DR' AND fyDeclared >= '2015'`

I don't see Hurricane Dorian declared for Polk county, but I see it declared for Martin, Florida (12085).

Are Dorian/Matthew supposed to be declared for Polk county?

**Comment by ljpaul** [comment]
Looks to be an emergency (ER) and not a major disaster declaration (DR).

```
SELECT *
FROM [RED_DR].[dbo].[FEMA_disasters]
WHERE [declarationTitle] LIKE '%DORI%'
AND [fipsStateCode] = '12' AND [fipsCountyCode] = '105'
```

https://www.fema.gov/disaster/3419

**Comment by ljpaul** [comment]
@iobik I think this can be closed, as this was not an actual disaster declaration but an emergency declaration.

**Comment by iobik** [comment]
I think we should add this additional text to make it clear to the users that the platform does not provide information on FEMA Emergency Declaration. Thank you!

![image](https://user-images.githubusercontent.com/71714873/97131334-42aaa400-171a-11eb-819f-3f0da3a8e4a6.png)

**Comment by soichih** [comment]
Updated it to this
