### ISSUE TITLE
Remove K (thousand) from the BVI visualization

### ISSUE THREAD

**Issue by iobik** [soichih/apred#19]
Remove K (thousand) from the BVI visualization since the complete numbers are being displayed.

![image](https://user-images.githubusercontent.com/71714873/93904587-ff4ab900-fcc7-11ea-94cd-10b0f6036098.png)

**Comment by soichih** [comment]
the "." inside the number "15.185K" is a decimal point (for U.S. default locale) so without K, it means 15.185 businesses, not 15,185 businesses. So I think that's why plotlyjs is adding k there?
