### ISSUE TITLE
Change the 3D visualizations on the EDA Awards section on the home page.

### ISSUE THREAD

**Issue by iobik** [soichih/apred#22]
The 3D visualizations are not proportional and do not describe the data clearly enough. Some options include using borders or shading to represent the counties that were awarded EDA funds instead of the way they are being presented at the moment?

![image](https://user-images.githubusercontent.com/71714873/93909833-39b75480-fcce-11ea-975c-45523a24b977.png)

**Comment by wliao1** [comment]
Issue needs further discussion; Ike to follow up w/ specific design changes.

**Comment by soichih** [comment]
> The 3D visualizations are not proportional 
This should not be true. The hight of the bar should be proportional to the `award_amount`. However, infrastructure fundings greatly overshadow non-infrastructure fundings. I think it might make sense to show them separately, or use different colors, etc. So that non-infrastructure fundings do't gets "washed out"?

**Comment by wliao1** [comment]
I agree that we should separate views for infrastructure and non-infrastructure for the exact reasons you mentioned.

**Comment by soichih** [comment]
I've updated the eda awards page to show eda awards for different purposes separately.

**Comment by soichih** [comment]
I've experimented with various different approaches to show EDA awards.

@iobik thinks showing counties with EDA funding awarded and detailing various awards in popup might be a better approach. Here is what that approach would look like.

![image](https://user-images.githubusercontent.com/923896/108604857-5f7c7e80-737e-11eb-904b-80655d458afd.png)

@iobik Please let me know if you like this approach.

**Comment by iobik** [comment]
I love what I'm seeing. I think the stakeholders will like it as well. Thank you for update.
