### ISSUE TITLE
Reorganize the county detail page into multiple tabs

### ISSUE THREAD

**Issue by iobik** [soichih/apred#23]
Add at the top to allow users to navigate the platform without having to scroll through the platform. The navigation links on the sidebar only appear when the user scrolls down.

![image](https://user-images.githubusercontent.com/71714873/93911556-8ac84800-fcd0-11ea-95c6-ef6356e37c90.png)

**Comment by soichih** [comment]
@iobik Can you explain what you mean by "The navigation links on the sidebar only appear when the user scrolls down"? As far as I can tell, the sidemenu is visible without having to scroll the page. 

![image](https://user-images.githubusercontent.com/923896/94595947-74366980-0259-11eb-88ac-d7153f69b2e9.png)

You mentioned a few times that you want the menu to show even when the screen is narrower. I can make the adjustment if you'd like me to show the sidebar menu with narrower screen.

**Comment by soichih** [comment]
I think I can try re-organizing the page into multiple tabs.

**Comment by soichih** [comment]
This should also solve the issue of slow page loading for each county.
