### ISSUE TITLE
Review the color pallet of the disaster resilience visualization on the home page

### ISSUE THREAD

**Issue by iobik** [soichih/apred#24]
Add brief information on the data source and how it was calculated.

![image](https://user-images.githubusercontent.com/71714873/93911846-f1e5fc80-fcd0-11ea-8093-38d1ad40881f.png)

**Comment by wliao1** [comment]
From discussion w/ Ike: users will want to get a sense of their region's resiliency. Having a border to separate state territories might help make this easier to evaluate.

**Comment by soichih** [comment]
How about this for the map descriptions?

**Comment by soichih** [comment]
Adjusted layer ordering also.
