### ISSUE TITLE
Provide information according to EDDs

### ISSUE THREAD

**Issue by iobik** [soichih/apred#25]
"Can we get the information for the regions that we manage? So basically, a higher resolution of data grouping into EDD regions." Carol/Logan to provide shape files for Soichi.

**Comment by soichih** [comment]
@ljpaul Do you have any data you can share so I can start looking into this?

**Comment by ljpaul** [comment]
Sorry.

We can get the shapefiles, but we do not currently have our data setup to be able to properly aggregate up to different levels.

**Comment by soichih** [comment]
Since we now have EDD regions info, we could aggregate data for each region.

**Comment by iobik** [comment]
@soichih What's the status?

**Comment by soichih** [comment]
If there is any suggestion on which information to aggregate across EDD, I could prototype that.

**Comment by soichih** [comment]
I am going to close this issue as it requires substantial modifications on both the backend and UI components to aggregate information at EDD level.
