### ISSUE TITLE
Add additional subtext under APRED header

### ISSUE THREAD

**Issue by wliao1** [soichih/apred#27]
<img width="613" alt="Screen Shot 2020-09-24 at 11 34 53 AM" src="https://user-images.githubusercontent.com/24637486/94167039-06093580-fe5a-11ea-93cb-992c2a980dcc.png">

Add "**For testing purposes only. Not for public use or for supporting current EDA applications.**"

**Comment by soichih** [comment]
I've added the text under the top menu bar

**Comment by soichih** [comment]
![image](https://user-images.githubusercontent.com/923896/94578010-329bc380-0245-11eb-8b3e-ae7a3b3642b5.png)

**Comment by wliao1** [comment]
Perfect, thank you!
