### ISSUE TITLE
Show information on the types of disaster that were funded by the EDA

### ISSUE THREAD

**Issue by iobik** [soichih/apred#32]
**Home page:** How can we tell which disaster type was funded on the EDA Disaster Supplemental Visualization section? For example, 'there may be one disaster, and there could be multiple disasters. Is there a way to tell?' 

![image](https://user-images.githubusercontent.com/71714873/95034657-8c125100-0690-11eb-8875-21aaef97cff3.png)

**Comment by soichih** [comment]
@iobik @ljpaul Is there a linking between EDA funding and the disaster declarations to answer this question?

**Comment by ljpaul** [comment]
There is a link between the EDA funding and the Disaster Declarations, but it is not a direct link. (My regular machine with all my DB access is getting its hard drive replaced right now so I cannot log in. When I get it back tomorrow I can make a query.)

**Comment by iobik** [comment]
This issue might be redundant since the page includes information on disaster and non-disaster awards?
