### ISSUE TITLE
What do these numbers mean and are they necessary?

### ISSUE THREAD

**Issue by iobik** [soichih/apred#35]
Numbers in the top right of each graph do not have any reference and therefore cannot be interpreted.

![image](https://user-images.githubusercontent.com/71714873/95035553-6d618980-0693-11eb-8396-1fdfea0bcde5.png)

**Comment by ljpaul** [comment]
Those are the index numbers from the DB. They do not need to be on here. (Although they are helpful for us internally, but not necessary.)

**Comment by ljpaul** [comment]
These can be removed.

**Comment by iobik** [comment]
@soichih Please, can you remove those numbers for the visualization? Thank you!
