### ISSUE TITLE
Highlight all our data sources

### ISSUE THREAD

**Issue by iobik** [soichih/apred#40]
State the name of the data sources.  This approach will help to answer questions about the authenticity and authority of the data we are presenting on the platform.

**Comment by soichih** [comment]
For example, add this sentence under the Disaster Resilience section

```
The resilience scores are calculated using information collected by the U.S. Census using formulas defined by Cutters, et all. 
```

**Comment by soichih** [comment]
I've added the sentence that I proposed under disaster Declarations tab. I am closing this as I believe is duplicate of #39.
