### ISSUE TITLE
Add a print/export visualization feature

### ISSUE THREAD

**Issue by iobik** [soichih/apred#41]
Add a feature to allow the users to export the visualizations (Different from the data download issue). The goal is to allow the users to add the visualizations to their presentations etc. We've discussed about this briefly but I wanted to make it an issue to allow for tracking.

**Comment by soichih** [comment]
I don't think we should implement tool that already exists to do this.

For Windows Users
> Select the Start  button, type snipping tool in the search box on the taskbar, and then select Snipping Tool from the list of **results.**

For Linux Users
>  Install *flameshot* (`apt install flameshot`)

For Mac Users
> Press Shift-Command-5 (or use Launchpad) to open Screenshot and display the tools. Click a dotted box to select the portion of the screen to screenshot.

**Comment by soichih** [comment]
For downloading the raw data for each graph, I believe it is addressed in #20
