### ISSUE TITLE
Can we compare our county to a neighboring county?

### ISSUE THREAD

**Issue by iobik** [soichih/apred#42]
How can we compare our county to a neighboring county or another county with similar demographics and economic stature? I am leaving this open as we have gotten this request multiple times.

**Comment by soichih** [comment]
I've been working on this, and so far user can select individual counties to compare, or enter a EDA region name to repopulate the list of counties to compare. 

![image](https://user-images.githubusercontent.com/923896/107564973-11fb5700-6bb1-11eb-8833-de5417bc8136.png)

Once the county names are entered, it can display graphs showing data from multiple counties together like this..

![image](https://user-images.githubusercontent.com/923896/107564941-03ad3b00-6bb1-11eb-909f-4c2aed6f2d29.png)
