### ISSUE TITLE
Add information on access to broadband to the Disaster Resilience section?

### ISSUE THREAD

**Issue by iobik** [soichih/apred#43]
Disaster Resilience >> Social Resilience section >> Communication Capacity. User quote "I probably would like to see access to broadband rather than telephone." 

![image](https://user-images.githubusercontent.com/71714873/95037513-4dcd5f80-0699-11eb-8dd0-5c6a88981813.png)

**Comment by iobik** [comment]
One of the things that we have to engage with Dr. Susan Cutter

**Comment by ljpaul** [comment]
I will check into this. When deciding what to include "duplicitous" indices were taken out. If I remember correctly there is a correlation within which they would not include the second index.

I think this really gets at the other ticket about contextualizing the disaster resilience. The users seem to want to know about the broadband, but (correct me if I am misremembering) that is because they are interested in that number... not because they think it has to do with disaster resilience?

**Comment by iobik** [comment]
Most of the users mentioned that having information on broadband access/resilience would be more useful to them than information on the percentage of household with telephone. **Social Resilience > Communication Capacity.**

**Comment by ljpaul** [comment]
Yep -- I agree that the information would probably be more useful... contextualized as "this data point would be more useful." I think I am trying to get at the distinction that the individual resilience indicators are small pieces that contribute to what is viewed as resilience within a community that comes from social science research. So independent of the resilience, this is something they want to know.

The gist of what I am (failing) to put into good words is that I think the people using the platform want to know that information, so we could definitely build it into the platform, but I am guessing that the request to see that information is note related to understanding the resilience of a community? Maybe we can chat about this at the end of our meeting on Thursday.

**Comment by soichih** [comment]
I second on @ljpaul 's comment.. resiliency scores allows us to compare between counties, or compare information longitudinally. If we keep updating how we measure resiliency, we can't use that to compare across time. 

If we have access to the raw sensus data used to compute resiliency (that includes broadband usage data), then I can load that and show them on another tab.

**Comment by iobik** [comment]
Ok. That makes sense. Can we add it to the County detail tab? @ljpaul @soichih

**Comment by iobik** [comment]
Checking in on this request. @soichih @ljpaul

**Comment by iobik** [comment]
@soichih @ljpaul  What's the status of adding this information to the County Detail page?

**Comment by soichih** [comment]
I haven't heard about "broadband access" data.

**Comment by iobik** [comment]
@ljpaul Please, how do we go about adding information on broadband to the county detail page?

**Comment by iobik** [comment]
@ljpaul Please, do we have any update on this issue?

**Comment by ljpaul** [comment]
We can pull the data, but I do not think it should go into the resilience data. Is this a separate data item that needs to go into another place?

https://data.census.gov/cedsci/table?q=ACSDT1Y2019.B28002&tid=ACSDT1Y2019.B28002&hidePreview=true

```
SELECT
	RIGHT(a.[geo_id],5) [fips]
	, a.[time_id] [year]
	, a.[data] [total_households]
	, b.[data] [total_households_broadband]
FROM [stats_dms5].[dbo].[ACS_common_items_extract] a
JOIN [stats_dms5].[dbo].[GEOGRAPHY_NAME] g ON g.[geo_id] = a.[geo_id] AND g.[sumlev] = '050'
LEFT JOIN (
	SELECT [geo_id], [time_id], [data] FROM [stats_dms5].[dbo].[ACS_common_items_extract] WHERE [code_id] = '912'
) b ON b.[geo_id] = a.[geo_id] AND b.[time_id] = a.[time_id]
WHERE a.[code_id] = '304'
	AND a.[time_id] = '2019'
```

This is for 2019. Can remove year to get all data over time.

```
code_id	description
304	Households
912	Total households with a broadband Internet subscription
```

**Comment by iobik** [comment]
@soichih Any update on this?

**Comment by soichih** [comment]
I've added it like this (on dev)

![image](https://user-images.githubusercontent.com/923896/115093633-fa11bd80-9ee8-11eb-90ac-e386483db219.png)

**Comment by iobik** [comment]
Awesome! This update looks really good. Thank you!
