### ISSUE TITLE
Adjust the summary of the storm history section

### ISSUE THREAD

**Issue by iobik** [soichih/apred#44]
1) In the first sentence change 'event' to 'events.'
2) Edit the information on the second paragraph of the storm history section?

A user proposed the below description: 

'Because the data collection types and total types have changed over the years it seems like it might be best to say that, “**Data collected before 1996 was a developing system. Less information was recorded as the database of storm information developed from 1954.  Since 1996, a 48 event system was implemented with consistency thus producing more accurate and reliable data.”**"

![image](https://user-images.githubusercontent.com/71714873/95037686-d2b87900-0699-11eb-8327-50146c4e3b0d.png)

**Comment by soichih** [comment]
Let's update the following text on the platform 

> Storm data has gone through many changes and versions over the years. The source data ingested into the database are widely varied and leads to many questions about the precision and accuracy of the location data. Please see https://www.ncdc.noaa.gov/stormevents/faq.jsp for more detail.

To this

> Storm data has gone through many changes and versions over the years. The source data ingested into the database are widely varied and leads to many questions about the precision and accuracy of the location data. For example, data collected before 1996 was a developing system. Less information was recorded as the database of storm information developed from 1954. Since 1996, a 48-event system was implemented with consistency thus producing more accurate and reliable data. Please see https://www.ncdc.noaa.gov/stormevents/faq.jsp for more detail.

For example? Can you compose an updated text so I can replace it?

**Comment by blj4** [comment]
I would also add "the" before "1950s" in the first sentence.

**Comment by soichih** [comment]
I've updated the text.
