### ISSUE TITLE
Add information on the five year ACS per capita income to the top section of the dashboard. 

### ISSUE THREAD

**Issue by iobik** [soichih/apred#47]
This is a new feature/data source request. I will reach out to Carol to schedule a meeting so we can discuss implementation strategies. I envisage that this information will be added to the static sidebar when move the navigation menu to the top bar.

**Comment by ljpaul** [comment]
@soichih here is the query

`select * from stats4.dbo.pcpi_uscnty WHERE year = '2018' AND countyfips <> '000' AND LINECODE = '0030'`

You can change the year as you see fit or use this one to grab the latest year.

`select * from stats4.dbo.pcpi_uscnty WHERE year = (SELECT TOP (1) year FROM stats4.dbo.pcpi_uscnty ORDER BY year DESC) AND countyfips <> '000' AND LINECODE = '0030'`

**Comment by iobik** [comment]
Thank you, Logan.

**Comment by soichih** [comment]
I've added it to the County Detail page
![image](https://user-images.githubusercontent.com/923896/97474105-1cefeb80-1922-11eb-95bf-6c5049936658.png)

**Comment by iobik** [comment]
Thank you! @soichih
