### ISSUE TITLE
population estimates by age

### ISSUE THREAD

**Issue by ljpaul** [soichih/apred#48]
Switch to `[stats4].[dbo].[poparo_uscnty]`

**Comment by soichih** [comment]
I've switched to `poparo_uscnty` table. I am now seeing the population data all the way from 1990!

However, I've noticed that this table doesn't contain pop_density column like `c2k_uscnty_acs` did. I am not sure what to do, so for now I am going to pull just this field from the old table.

```
         SELECT p.*, c.pop_density
             FROM [stats4].[dbo].[poparo_uscnty] p
             LEFT JOIN [stats4].[dbo].[c2k_uscnty_acs] c
                 ON c.statefips = p.statefips and c.countyfips = p.countyfips and c.year = p.year
```

**Comment by iobik** [comment]
I'm closing this for now. Will revisit in the future if an issues arises about pulling population density data from the old table. Thank you.
