### ISSUE TITLE
Add text to highlight multi-county awards

### ISSUE THREAD

**Issue by iobik** [soichih/apred#50]
Add a text to highlight an award that is split between multiple counties? 

![image](https://user-images.githubusercontent.com/71714873/97130081-c95d8200-1716-11eb-9d7c-e4450ea570e9.png)

**Comment by soichih** [comment]
added a label
![image](https://user-images.githubusercontent.com/923896/97483419-c9839a80-192d-11eb-903e-44631978d4da.png)
