### ISSUE TITLE
Population by Age Graph Not Showing 2015

### ISSUE THREAD

**Issue by blj4** [soichih/apred#59]
When you hover over the graph, it is not showing the 2015 data. It goes from 2014 to 2016.

**Comment by soichih** [comment]
@blj4 which county are you seeing this issue on? 

Also, this issue might be fixed as part of #48

**Comment by blj4** [comment]
It was Marion County, Indiana. I just checked and it is fixed by switching to the new data source. Thanks, Soichi!
