### ISSUE TITLE
Business Vulnerability and Disaster Resilience Graphs Not Showing All Digits

### ISSUE THREAD

**Issue by blj4** [soichih/apred#61]
The graphs on the Business Vulnerability and Disaster Resilience tabs are not showing all of the digits when you hover over the 2018 data. For example, in Marion County, Indiana, when you hover over the employees in Construction, the number should be 28,716, but it is only showing 2871. It appears this is only happening with 2018. See image below.
![image](https://user-images.githubusercontent.com/73551173/97450952-a5ae5d80-1909-11eb-9c73-7d129c31b66d.png)

I would also format the numbers in the hover AND on the vertical axis to have commas.

**Comment by soichih** [comment]
Adjusted the font/size position of tooltip, but then I decided to display all numbers by default.

![image](https://user-images.githubusercontent.com/923896/98554238-80591200-226e-11eb-8cdd-60d92d3f9e78.png)

**Comment by blj4** [comment]
This issue is still happening on the Disaster Resilience tab graphs. When you hover, it's cutting off the end of the 2018 data.

**Comment by iobik** [comment]
Resolved with changes to the visualization format. Thank you!
