### ISSUE TITLE
Disaster Resilience Detail

### ISSUE THREAD

**Issue by blj4** [soichih/apred#63]
The detail that is shown beneath each graph on the Disaster Resilience tab is helpful for verification, but the codes won't mean anything to the public. I would remove that before release. See image below.
![image](https://user-images.githubusercontent.com/73551173/97454942-b1038800-190d-11eb-9e5e-4c2752b9bf04.png)

**Comment by soichih** [comment]
Yes, I think it would be nice if we could have more information, but we at least show what those code means

> Codes 770 (Language Spoken at Home: Population with age 5 and above) 
> and 771 (Language Spoken at Home: Population with age 5 and above: English Only) 

I think it's worth keeping them, rather than completely removing them?

**Comment by blj4** [comment]
That’s probably someone else’s call, but I would say listing the data items without the code numbers would be sufficient. Users without access to the database won’t know what the codes mean, even with the descriptions listed.

From: Soichi Hayashi ***@***.***>
Sent: Friday, March 26, 2021 12:35 PM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Author ***@***.***>
Subject: [External] Re: [soichih/apred] Disaster Resilience Detail (#63)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Yes, I think it would be nice if we could have more information, but we at least show what those code means

Codes 770 (Language Spoken at Home: Population with age 5 and above)
and 771 (Language Spoken at Home: Population with age 5 and above: English Only)

I think it's worth keeping them, rather than completely removing them?

**Comment by iobik** [comment]
@blj4 @soichih Are we good on this issue?

**Comment by ljpaul** [comment]
I think so. I would like to leave the codes, as it allows for a user to more easily replicate our calculation.
