### ISSUE TITLE
Single Sector Employment Dependence

### ISSUE THREAD

**Issue by blj4** [soichih/apred#64]
I'm not sure what Single Sector Employment Dependence (on the Disaster Resilience tab) means or how it's calculated. I can't recreate the numbers. See image below.
![image](https://user-images.githubusercontent.com/73551173/97462393-08f1bd00-1915-11eb-8114-ac05cc2edc0c.png)

**Comment by soichih** [comment]
Could be addressed as part of #45

**Comment by ljpaul** [comment]
This one should say 1- according to the query. I will add that change to the descriptive text.

**Comment by soichih** [comment]
It still shows this
> Calculation: ([NAICS 11] + [NAICS 21]) / [300]
Do I need to refreshing some caching somewhere?

**Comment by iobik** [comment]
@ljpaul @soichih What is the status of this issue?

**Comment by ljpaul** [comment]
Updated and will pull in the next data refresh.
