### ISSUE TITLE
Cannot Verify Health Access, Housing Type, and Innovation on Disaster Resilience Tab

### ISSUE THREAD

**Issue by blj4** [soichih/apred#65]
I'm not sure how to verify the Health Access, Housing Type, and Innovation data on the Disaster Resilience tab. I don't think those NAICS codes exist for Health Access, I don't see Table B25025 on ACS for Housing Type, and I don't know what the creative class NAICS codes are. See images below.

![image](https://user-images.githubusercontent.com/73551173/97467390-85d36580-191a-11eb-8cf4-e72b11806180.png)
![image](https://user-images.githubusercontent.com/73551173/97467812-f4b0be80-191a-11eb-8c32-17fe080c3b62.png)
![image](https://user-images.githubusercontent.com/73551173/97470624-1fe8dd00-191e-11eb-9621-02c33faa733c.png)

**Comment by ljpaul** [comment]
For health access, I will change the text. It is not NAICS it is the occupational estimates from `occest_uscnty_ibrc_new`.

For the housing type, I will correct it to say `B25024`.

Creative Class Occupations: https://www.ers.usda.gov/data-products/creative-class-county-codes/documentation/

**Comment by iobik** [comment]
@ljpaul Any updates on this issue?

**Comment by ljpaul** [comment]
Fixed in the DB and will update when the data is extracted again.
