### ISSUE TITLE
Per Capita/Per Square Mile Issue on Disaster Resilience Tab

### ISSUE THREAD

**Issue by blj4** [soichih/apred#66]
For Sheltering Need on the Disaster Resilience tab, should that be a percentage? It should just be a number, right? For example, Marion County, Indiana for 2018, it should be 0.4365, not 43.65%? See image below.
![image](https://user-images.githubusercontent.com/73551173/97468666-eca54e80-191b-11eb-9bfb-eb962c92bc70.png)

This also applies to the Health Access (physicians per capita) earlier on the page and Social Capital - Religion (religious organizations per capita), Social Capital - Civic Involvement (civic organizations per capita), and Social Capital - Advocacy (social advocacy organizations per capita) later on the page.

**Comment by soichih** [comment]
@ljpaul Should I change the y-axis units on Sheltering need to "/sq mile"? And all those "Health Access" graphs to "/capita"?

**Comment by ljpaul** [comment]
No, these are normalized so it is on a 0-1 scale which makes it a percentage. It is the percentile that the county is within the nation.

**Comment by soichih** [comment]
I think we should update the description of the graph to indicate that it is normalized? Something like

> Percentile of the number of hotels and motels per square mile normalized to 0-1 within the nation.

**Comment by iobik** [comment]
@blj4 @soichih What is the status of this issue?

**Comment by blj4** [comment]
I agree with Soichi’s suggested description update. Does that make sense to @ljpaul?

From: iobik ***@***.***>
Sent: Monday, March 29, 2021 10:32 PM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [soichih/apred] Per Capita/Per Square Mile Issue on Disaster Resilience Tab (#66)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


@blj4<https://github.com/blj4> @soichih<https://github.com/soichih> What is the status of this issue?

**Comment by iobik** [comment]
@ljpaul What do you think about these changes?

**Comment by ljpaul** [comment]
Since all of the measures are normalized, do we just want to have something at the top that indicates as such instead of one-off for each measure?

**Comment by soichih** [comment]
@ljpaul Are you sure that *all* disaster resilience graphs are normalized? If they are all normalized, I would think that U.S. average bar (the blue line) should all be at 50% on all graphs for all years. 

Also, there are graphs like this one
![image](https://user-images.githubusercontent.com/923896/115096328-95f3f700-9ef2-11eb-9bc7-8340877ca4b6.png)
that is clearly not showing normalized "percentile" information. Can you explain what these graphs are showing?

**Comment by ljpaul** [comment]
I'm fairly certain. The data source is compiled through some views that take care of the normalization. Checking into this one now... 

From the `dr_data_norm` table for this measure (`27`) it seems like there aren't any values that are that small. The average for all the years should be hovering around 49% according to my quick query.

What county is this?

**Comment by soichih** [comment]
Here are some counties that I've looked at

https://ctil.iu.edu/apred/#/county/18181
https://ctil.iu.edu/apred/#/county/18105

Here are the graphs for Monroe county

![image](https://user-images.githubusercontent.com/923896/115253917-dde56a80-a0fa-11eb-9b27-c709fa8f5f56.png)
![image](https://user-images.githubusercontent.com/923896/115253975-eb025980-a0fa-11eb-8811-ea11d22c3c4e.png)

**Comment by ljpaul** [comment]
What is the data source?

Looking up Monroe County `18105`...

Raw Data `dr_data`
```
year	        measure_value
2012      	0.00263
2013      	0.002723
2014      	0.002661
2015      	0.002549
2016      	0.002356
2017      	0.002533
2018      	0.002454
```

Normalized Data `dr_data_norm`
```
year	        measure_value_normalized
2012      	0.663405607521331
2013      	0.675124390484661
2014      	0.66307945587923
2015      	0.632979979984783
2016      	0.666103663037569
2017      	0.697800540371397
2018      	0.689771626765969
```

So it seems like this is actually pulling the raw data.

**Comment by soichih** [comment]
I am using `dr_data`
> https://github.com/soichih/apred/blob/master/backend/bin/extract/statsamerica_dr.js#L15

@iobik @blj4 Do we want to show raw data, or normalized data? For me, raw data is more interesting because I have more intuitive understanding of what various DR values are showing. I think normalized data can be more useful if we want to compare between different counties?

**Comment by blj4** [comment]
I don’t think I can answer this. Up to Ike, Logan, etc.

From: Soichi Hayashi ***@***.***>
Sent: Tuesday, April 20, 2021 10:55 AM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [soichih/apred] Per Capita/Per Square Mile Issue on Disaster Resilience Tab (#66)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


I am using dr_data

https://github.com/soichih/apred/blob/master/backend/bin/extract/statsamerica_dr.js#L15

@iobik<https://github.com/iobik> @blj4<https://github.com/blj4> Do we want to show raw data, or normalized data? For me, raw data is more interesting because I have more intuitive understanding of what various DR values are showing. I think normalized data can be more useful if we want to compare between different counties?

**Comment by ljpaul** [comment]
Continue to display raw data. Some values will be exceptionally small but that is just how the world spins.
