### ISSUE TITLE
Increase the font size

### ISSUE THREAD

**Issue by iobik** [soichih/apred#71]
Increase the font size to match the size of the font beside the text.

![image](https://user-images.githubusercontent.com/71714873/101380394-6f0e2000-3883-11eb-8b2b-3108c8d2ca16.png)

**Comment by soichih** [comment]
I've updated the tag size, and also updated the layout to have the dates on the left side of the bar (standard for most vertical event list)

![image](https://user-images.githubusercontent.com/923896/110014921-5af68500-7cf1-11eb-9e6f-a3aed3f01abf.png)

**Comment by iobik** [comment]
Good job! Looks cleaner now. Thanks
