### ISSUE TITLE
How to handle charts with no data

### ISSUE THREAD

**Issue by iobik** [soichih/apred#73]
For the BVI, can we display no data instead of showing empty charts which appears like there is an error or something is broken.

![image](https://user-images.githubusercontent.com/71714873/101381250-84377e80-3884-11eb-9f9d-e8543dc48f95.png)

**Comment by ljpaul** [comment]
Vulnerable businesses/industries come from within the following top level NAICS codes. (Bolded.)

**Sector 11: Agriculture, Forestry, Fishing and Hunting**
Sector 21: Mining, Quarrying, and Oil and Gas Extraction
**Sector 22: Utilities**
Sector 23: Construction
**Sector 31-33: Manufacturing**
Sector 42: Wholesale Trade
**Sector 44-45: Retail Trade**
**Sector 48-49: Transportation and Warehousing**
**Sector 51: Information**
Sector 52: Finance and Insurance
Sector 53: Real Estate and Rental and Leasing
Sector 54: Professional, Scientific, and Technical Services
Sector 55: Management of Companies and Enterprises
Sector 56: Administrative and Support and Waste Management and Remediation Services
Sector 61: Educational Services
Sector 62: Health Care and Social Assistance
Sector 71: Arts, Entertainment, and Recreation
**Sector 72: Accommodation and Food Services**
Sector 81: Other Services (except Public Administration)
Sector 92: Public Administration

```
-- Information (51)
    OR [naics_code] IN (
        '517110','517210','517410','518210'
    )
    -- Agriculture, Forestry, Fishing, and Hunting (11)
    OR [naics_code] IN (
        '111110','111120','111130','111140','111150','111160',
        '111199','111211','111219','111310','111320','111331',
        '111332','111333','111334','111335','111336','111339',
        '111411','111419','111421','111422','111910','111920',
        '111930','111940','111991','111992','111998','112111',
        '112120','112210','112330','112340','112320','112390'
    )
    -- Utilities (22)
    OR [naics_code] IN (
        '221111','221112','221113','221114','221115','221116',
        '221117','221118','221121','221122','221210','221310',
        '221320'
    )
-- Manufacturing (31-33)
    OR [naics_code] IN (
        '31-33'
    )
    -- Retail Trade (44-45)
    OR [naics_code] IN (
        '44-45'
    )
    -- Transportation and Warehousing (48-49)
    OR [naics_code] IN (
        '493110','493120','493130','493190'
    )
    -- Accommodation and Food Services (72)
    OR [naics_code] IN (
        '722410','722511','722513','722514'
    )
```

**Comment by soichih** [comment]
@ljpaul Just to be sure.. you said that I should only display charts for those 7 sectors, correct? Other sectors will never be populated?

**Comment by soichih** [comment]
I've updated BVI page so that graphs with no vulnerable establishments/employments will be hidden under a toggle button.

![image](https://user-images.githubusercontent.com/923896/103304883-c3ff0b00-49d7-11eb-8007-f8a05a897d47.png)

I believe this addresses many of the issues/requests that we've had on this page.

**Comment by ljpaul** [comment]
This looks great. Apologies for not seeing your earlier comment to verify.

**Comment by iobik** [comment]
Good job! Closing this for now.
