### ISSUE TITLE
EDA Supplemental Awards tool: how are ‘infrastructure’ and ‘construction’ categories distinguished?

### ISSUE THREAD

**Issue by wliao1** [soichih/apred#82]
Tester mentioned that 'infrastructure' and 'construction' categories are usually tied to the same project. 

Bernadette mentioned this seeming peculiar as well.

Is this a field in the data from EDA or did we infer? Either way we can discuss how to consolidate / address.

**Comment by wliao1** [comment]
![Uploading image.png…]()

**Comment by soichih** [comment]
Did you mean to upload an image? It looks like the attachment didn't work?

**Comment by wliao1** [comment]
![image](https://user-images.githubusercontent.com/24637486/106770921-7005c880-660c-11eb-8b12-e92866e18fc3.png)

I did, that's weird. This should show up now - just wanted to highlight the area in the platform that I'm referring too.

**Comment by soichih** [comment]
I don't think construction and infrastructure are tied to the same projects as I am seeing a completely different set of records. 

Construction
![image](https://user-images.githubusercontent.com/923896/106779064-9c254780-6614-11eb-8846-e898e71261ad.png)

Infrastructure
![image](https://user-images.githubusercontent.com/923896/106779097-a6dfdc80-6614-11eb-90f6-f41b3dd46ca0.png)

But I agree that we should have descriptions for each "purpose". Does EDA publish the meaning of "purpose" field?

**Comment by wliao1** [comment]
Not to my knowledge, @ljpaul are you aware of any such definitions being available?

**Comment by soichih** [comment]
From our email conversation, it seems that Non-Construction / Construction purposes are for 2012 supplemental awards. 

So I think we want to show this in the following format?

![image](https://user-images.githubusercontent.com/923896/112667765-0ea3ee00-8e34-11eb-8b62-464d0586d7c3.png)

**Comment by iobik** [comment]
This new update is much better. Thank you!
