### ISSUE TITLE
A glitch with the BVI Visualization?

### ISSUE THREAD

**Issue by iobik** [soichih/apred#83]
BVI visualization formatting requires adjustment. I checked couple of counties, Monroe & Delaware Indiana, and other counties.

![image](https://user-images.githubusercontent.com/71714873/107136430-0bc75b00-68d1-11eb-83f8-58d3285c6f49.png)

**Comment by soichih** [comment]
I am thinking about using plotly graph instead of my custom (buggy) graph. Please see #84

**Comment by iobik** [comment]
Thank you for updating the visualization. Looks much better now.
