### ISSUE TITLE
Keep the circle for only the vulnerable businesses

### ISSUE THREAD

**Issue by iobik** [soichih/apred#84]
Keep the circle for only the vulnerable businesses. This formatting will help to the draw the users attention to the line that displays information on vulnerability first.

![image](https://user-images.githubusercontent.com/71714873/107136492-a9228f00-68d1-11eb-9d40-84194ffa02e4.png)

**Comment by soichih** [comment]
I am thinking about replacing this graph with plotly graph. What do you think about using a graph like this?

**Comment by iobik** [comment]
Great job!
