### ISSUE TITLE
BVI on some county missing values 

### ISSUE THREAD

**Issue by soichih** [soichih/apred#88]
I've noticed some odd looking data for some counties

![image](https://user-images.githubusercontent.com/923896/107241694-39a7bf00-69f9-11eb-8baa-1ad2cc10c79b.png)

This happens because the employment total is missing some values (the SQL query reset it to 0), and the graph subtracts vulnerable employment from the total employment to show the non-vulnerable employments in a stacked bar graph.

(fips 18181)

```
"emp": [
0,
0,
0,
79,
74,
94,
80
],
"emp_v": [
52,
49,
51,
53,
53,
0,
0
]
```

I am wondering.. why some numbers are missing @ljpaul ?

Also, in case of total employment < vulnerable employment, should I hide the data for that year?

**Comment by soichih** [comment]
I also saw this county. 

![image](https://user-images.githubusercontent.com/923896/107245725-77a6e200-69fd-11eb-86ea-cf52b5188a87.png)

This one seems to be missing both total and vulnerable employment - so the net result is that the graph just goes missing. I think white county should look like this also?

**Comment by ljpaul** [comment]
I think this is a suppression-related issue because there are so few people employed in the 6 digit codes that we defined as "vulnerable," but establishments are not suppressed. Let me check with Bethany/Brittany/Carol; I just emailed them.

Example Query: SELECT * FROM [stats4].[dbo].[cbp_uscnty] WHERE [statefips] = '18' AND [countyfips] = '181' AND [naics_code] = '51' AND [year] IN ('2012','2013','2014','2015')

**Comment by iobik** [comment]
@ljpaul @soichih Any updates?

**Comment by ljpaul** [comment]
We cannot do anything about the suppression, so it would probably be best to add something to the UI to indicate that data is suppressed and thus we cannot display.

**Comment by iobik** [comment]
@soichih What do you think

**Comment by soichih** [comment]
We are replacing NULL value with 0 during the data extraction stage.

```
 23     , ISNULL(a.[estab_total],0) AS estab_total
 24     , ISNULL(b.[estab_total],0) AS estab_vuln_total
 25     , CASE WHEN a.[estab_total] = 0 THEN 0 ELSE ISNULL(b.[estab_total],0)/a.[estab_total] END AS estab_vuln_pct
 26     , ISNULL(a.[mm_employees],0) AS emp_total
 27     , ISNULL(b.[mm_employees], 0) AS emp_vuln_total
 28     , CASE WHEN a.[mm_employees] = 0 THEN 0 ELSE ISNULL(b.[mm_employees],0)/a.[mm_employees] END AS emp_vuln_pct
 29 FROM [stats4].[dbo].[cbp_uscnty] a 
```

@ljpaul do we need to update the query so I can tell if the value is missing? Or should I just assume all 0 values as "missing"? I think there are a few counties with 0 as real data.. though.

**Comment by soichih** [comment]
@ljpaul I understand about the suppression.

While I was working on this, I've noticed something odd. When you look at the screenshot I posted on feb/4 above, you will notice that you see data displayed for Information (code 51) for 2017/2018 with only non-vulnerable graphs (gray ones). However, according to the records that I am pulling from the database, this county "18181" (White County, Indiana) now are missing records for 2017 and 2018 all together.

![image](https://user-images.githubusercontent.com/923896/115095892-f124ea00-9ef0-11eb-8e11-02b0031038d0.png)

I am not sure if this is because of all the SQL query change we've been making (https://github.com/soichih/apred/commit/3b550e26869d309c4f2c8503dced9e753904af64) 

But now the last record I see for county 18181 for code 51 is 2016 (no 2017 nor 2018)

![image](https://user-images.githubusercontent.com/923896/115095917-11ed3f80-9ef1-11eb-93ee-98c05c2b425b.png)

Do we need to do anything about this?

**Comment by ljpaul** [comment]
I just updated the query in #99 to be a `LEFT OUTER JOIN` instead of a join. This appears to have fixed the issue for this county (and I assume a few others that we have not found yet) when there are employees or establishments but nothing in the vulnerable category.

**Comment by soichih** [comment]
@ljpaul I am now seeing a lot more records (I think close to x10 more data now!?). I see some records after 2016 now, naics_code is set to `null`. Do you know how to fix that?

![image](https://user-images.githubusercontent.com/923896/116271217-c5ee9600-a74d-11eb-8608-1ca7d5168729.png)

**Comment by ljpaul** [comment]
Fixed by changing from `b.[naics_code]` to `a.[naics_code]` in the other issue where all of the queries are.
