### ISSUE TITLE
top industries in a given county

### ISSUE THREAD

**Issue by ljpaul** [soichih/apred#91]
Here is a query from Bethany that grabs the employment in sectors so that we can display the biggest industries in a county. This is in `db1\stats4`.

```
SELECT TOP(10) a.statefips, a.countyfips, a.year, a.naics, b.naics_title, a.empl 
FROM cew_totown_n a, naics b
WHERE a.year = '2019' AND a.naics <> '00'
AND a.statefips = '18' AND a.countyfips = '097'
AND a.naics = b.naics_code
AND (a.naics LIKE '__' OR a.naics LIKE '__-__')
ORDER BY empl desc
```

We can edit this if you want to do a bigger ingestion, @soichih , but this is the table and data we can use. Looks like 2019 is the most recent year.

**Comment by soichih** [comment]
I've added the number.. What do you think?

![image](https://user-images.githubusercontent.com/923896/107984481-02f01c80-6f96-11eb-894c-3a5316a53fe6.png)

What is the unit for empl number? Is it in thousands? 

Also, if we have all the numbers for other industry, we might as well show numbers from other naics code and maybe show a pie chart?

**Comment by soichih** [comment]
Here is the pie chart version.

![image](https://user-images.githubusercontent.com/923896/107985304-d6d59b00-6f97-11eb-83d6-b256a45f6ed1.png)
![image](https://user-images.githubusercontent.com/923896/107985645-77c45600-6f98-11eb-8202-023c04ddee25.png)

Which do you prefer?

Also, for Monroe County, it's surprising that "Educational Services" is only 5.46%. Is that right?

**Comment by soichih** [comment]
Grouped all industries <5% into "others"

![image](https://user-images.githubusercontent.com/923896/107986434-084f6600-6f9a-11eb-9415-999fd0edee33.png)

**Comment by soichih** [comment]
This might be better?

**Comment by iobik** [comment]
Yes! This option looks better.

**Comment by ljpaul** [comment]
Agreed!

**Comment by iobik** [comment]
Good job friends!
