### ISSUE TITLE
Fix the visualizations on the county detail page

### ISSUE THREAD

**Issue by iobik** [soichih/apred#96]
The county detail page now contains a lot of visualization and might lead to information overload for new users.

I suggest we make the following visualizations optional. (i.e. remove from the default view but can be shown via the view more button).

1. Population
2. Population Density
3. GDP
4. Per Capita Income
5. Median Household Income
6. Per Capita Money Income
7. Per Capita Personal Income

**The visualization to remain on the default view includes:**

1. Population History
2. Racial Make up history
3. Unemployment rate
4. Top Industries

**Comment by soichih** [comment]
I've reorganized the county detail elements

**Comment by iobik** [comment]
Awesome! Thank you
